# ── Servidor ──────────────────────────────────────────────
server.port=8080

# ── SQLite ────────────────────────────────────────────────
# O arquivo será criado na pasta onde o jar for executado
spring.datasource.url=jdbc:sqlite:usermanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

# Desliga auto-configuração de Hibernate/JPA (não usamos)
spring.jpa.open-in-view=false

# ── Upload ────────────────────────────────────────────────
# Pasta onde as fotos serão salvas (relativa ao diretório de execução)
app.upload-dir=uploads

# Limite de tamanho do multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


# ── Log ───────────────────────────────────────────────────
logging.level.com.eyetec=DEBUG
spring.datasource.hikari.maximum-pool-size=1
